// This file was auto-generated by ML.NET Model Builder. 

using System;
using LanguageAppML.Model;

namespace LanguageAppML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

        }
        
    }
}
